version: '3.3'

services:
  database:
      image: postgres
      container_name: database
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: laravel_docker
      volumes:
        - ./postgres-data:/var/lib/postgresl/data
      ports:
        - '6000:5432'
  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database